version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - type: bind
        source: ${DataMountPoint}
        target: /var/lib/influxdb2
      - type: bind
        source: ${ConfMountPoint}
        target: /etc/influxdb2/
      - type: bind
        source: /etc/smartmeter/
        target: /marker
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${PASSWD}
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=Stromzähler
    command: /bin/bash -c "/entrypoint.sh"
    command: /bin/bash -c "exec touch /marker/started"
    command: /bin/bash -c "tail -f /dev/null" #Keep Container running forever...
