version: '3.3'

services:
  influxdb:
    image: influxdb:2.5.1
    ports:
      - '8086:8086'
    volumes:
      # Bind the data-dir to the host
      - ${DataMountPoint}:/var/lib/influxdb2:rw
      
      # Bind the config-dir to the host: 
      - ${ConfMountPoint}:/etc/influxdb2/:rw
      
      # Sync Time with host:  
      - /etc/localtime:/etc/localtime:ro
      #- type: bind
        #source: ${DataMountPoint}
        #target: /var/lib/influxdb2
          #      - type: bind
          #        source: ${ConfMountPoint}
          #        target: /etc/influxdb2/
          #      - type: bind
          #        source: /etc/smartmeter/
          #        target: /marker
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${PASSWD}
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=Stromzähler
        #    command: /bin/bash -c "/entrypoint.sh"
