version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Admin1234!
      - DOCKER_INFLUXDB_INIT_ORG=MyOrg
      - DOCKER_INFLUXDB_INIT_BUCKET=Stromzähler

volumes:
    influxdb-storage:
